package com.project.transaction.infrastructure.api.mapper;

import com.project.transaction.infrastructure.api.dto.TransferRequest;
import com.project.transaction.infrastructure.api.dto.TransferResponse;
import com.project.transaction.domain.usecase.TransactionInput;
import com.project.transaction.domain.model.TransactionRecordModel;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper responsible for data transformation between the Presentation (API) layer
 * and the Core Domain layer.
 * This ensures that external contracts (DTOs) remain decoupled from internal business models,
 * enforcing clean architectural boundaries.
 */
@Mapper(componentModel = "spring")
public interface TransactionApiMapper {

    /**
     * Converts the incoming API request payload into a domain-specific input model.
     *
     * @param request The data transfer object received from the client.
     * @return The internal domain input model ready for business logic processing.
     */
    TransactionInput toInput(TransferRequest request);

    /**
     * Converts the internal transaction record model into an outgoing response DTO.
     * Maps the internal database 'id' to the client-facing 'transactionId' for better clarity.
     *
     * @param model The completed transaction record generated by the domain layer.
     * @return The response payload to be sent back to the API client.
     */
    @Mapping(target = "transactionId", source = "id")
    TransferResponse toResponse(TransactionRecordModel model);
}