package com.project.transaction.domain.model;

import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

/**
 * Domain model representing a finalized historical transaction record.
 * This model resides in the core domain layer and is used to carry the result 
 * of a processed business use case outward to the presentation layer or infrastructure layer.
 * It is completely decoupled from database persistence entities and API DTOs.
 */
@Getter
@Builder
public class TransactionRecordModel {

    /**
     * The unique identifier of the transaction record.
     * Typically generated by the database upon persistence or assigned as a UUID during processing.
     */
    private String id;

    /**
     * The unique identifier of the user who initiated the transfer (the sender).
     */
    private String senderUserId;

    /**
     * The unique identifier of the user who received the funds.
     */
    private String receiverUserId;

    /**
     * The monetary amount that was transferred during this transaction.
     */
    private Double amount;

    /**
     * The exact date and time when the transaction was successfully processed and recorded.
     */
    private LocalDateTime transactionDate;

    /**
     * The final state of the transaction execution (e.g., "SUCCESS", "FAILED", "SUSPICIOUS").
     */
    private String status;
}