package com.project.user.infrastructure.api.mapper;

import com.project.user.infrastructure.api.dto.BasicUserResponse;
import com.project.user.infrastructure.api.dto.CreateUserRequest;
import com.project.user.infrastructure.api.dto.CreateUserResponse;
import com.project.user.domain.usecase.UserCreateInput;
import com.project.user.domain.model.UserModel;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper responsible for data transformation between the Presentation (API) layer
 * and the Core Domain layer.
 * This ensures that external contracts (DTOs) remain decoupled from internal business models,
 * enforcing strict clean architectural boundaries.
 */
@Mapper(componentModel = "spring")
public interface UserApiMapper {

    /**
     * Converts the incoming API request payload into a domain-specific input model.
     * Maps the API-facing 'password' field to the domain's 'rawPassword' field as a 
     * security reminder that the string is currently unhashed.
     *
     * @param request The data transfer object received from the client.
     * @return The internal domain input model ready for business logic processing.
     */
    @Mapping(target = "rawPassword", source = "password")
    UserCreateInput toInput(CreateUserRequest request);

    /**
     * Converts the internal user model into an outgoing, detailed response DTO.
     * Injects a constant status message to inform the client of the successful operation.
     *
     * @param model The completed user profile generated by the domain layer.
     * @return The detailed response payload to be sent back to the API client.
     */
    @Mapping(target = "statusMessage", constant = "User account successfully created.")
    CreateUserResponse toResponse(UserModel model);

    /**
     * Converts the internal user model into a lightweight, outgoing basic response DTO.
     * Used for dropdowns and list views where sensitive data (like emails) is stripped out.
     *
     * @param model The internal user model.
     * @return The lightweight DTO representation.
     */
    BasicUserResponse toBasicResponse(UserModel model);

    /**
     * Converts a list of internal user models into a list of basic response DTOs.
     * MapStruct automatically generates the underlying iteration and mapping logic for this.
     *
     * @param models The list of internal user models.
     * @return The list of lightweight DTOs ready for API transmission.
     */
    List<BasicUserResponse> toBasicResponseList(List<UserModel> models);
}
